modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/trueddd/yama-copper-pressure-plates/issues"
license = "CC0-1.0"

[[mixins]]
config = "yama_copper_plates.neoforge.mixins.json"

[[mods]]
modId = "yama_copper_plates"
version = "${mod_version}"
displayName = "Yama Copper Plates"
authors = "truetripled"
logoFile = "icon.png"
description = '''
This mod adds Vanilla-friendly copper pressure plates which can only be triggered by players.
'''

[[dependencies.yama_copper_plates]]
modId = "neoforge"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yama_copper_plates]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yama_copper_plates]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"
