modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/trueddd/yama-copper-pressure-plates/issues"
license = "CC0-1.0"

[[mods]]
modId = "yama_copper_plates"
version = "${version}"
displayName = "Yama Copper Plates"
authors = "truetripled"
logoFile = "icon.png"
description = '''
This mod adds Vanilla-friendly copper pressure plates which can only be triggered by players.
'''

[[dependencies.yama_copper_plates]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yama_copper_plates]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yama_copper_plates]]
modId = "architectury"
type = "required"
versionRange = "[17.0.6,)"
ordering = "AFTER"
side = "BOTH"
